# Generated by Django 4.2.3 on 2023-07-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
    ]
