# Generated by Django 4.2.3 on 2023-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Author", "Author"), ("Reader", "Reader")],
                default="Reader",
                max_length=6,
            ),
        ),
    ]
