# Generated by Django 4.2.3 on 2023-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authorName",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
    ]
