# Generated by Django 4.2.3 on 2023-07-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_page"),
    ]

    operations = [
        migrations.RemoveField(model_name="page", name="book",),
        migrations.RemoveField(model_name="page", name="text",),
    ]
