# Generated by Django 4.2.3 on 2023-07-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_page_book_remove_page_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.book",
            ),
        ),
        migrations.AddField(
            model_name="page", name="text", field=models.TextField(null=True),
        ),
    ]
