# Generated by Django 4.2.3 on 2023-07-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_page_book_page_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.book"
            ),
        ),
        migrations.AlterField(
            model_name="page", name="text", field=models.TextField(),
        ),
    ]
